<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>Study.LabWork2.Program</StartupObject> 
  </PropertyGroup>

  <Import Project="..\..\build.settings.props" />
  <Import Project="..\..\readme-generation.props" />
  <ItemGroup>
    <ProjectReference Include="..\Study.LabWork2.Abstractions\Study.LabWork2.Abstractions.csproj" />
  </ItemGroup>

</Project>
